package alapmuveletek;

import java.awt.AWTEventMulticaster;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;

public class Ablak extends javax.swing.JFrame {

    private String kerdes;
    private int valasz;
    
    public Ablak() {
        initComponents();
        
        DefaultComboBoxModel<String> dcbmMuveletek = new DefaultComboBoxModel<>(new String[]{"-- Válassz műveletet --", "Összeadás", "Kivonás", "Szorzás", "Osztás"});
        cbMuveletek.setModel(dcbmMuveletek);
        
        cbMuveletek.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (cbMuveletek.getSelectedItem().equals("Osztás")) {
                    int a = (int)(Math.random() * 100);
                    int b = (int)(Math.random() * 99 + 1);
                    valasz = a / b;
                    kerdes = a+" / "+b+" = ";
                    tfKerdes.setText(kerdes);
                }
            }
        });
        
        btnEllenoriz.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int userValasz = Integer.valueOf(tfValasz.getText());
                if (userValasz == valasz) {
                    tfVisszajelzes.setText("Helyes válasz!");
                }
                else {
                    tfVisszajelzes.setText("Rossz válasz!");
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAblak = new javax.swing.JPanel();
        cbMuveletek = new javax.swing.JComboBox<>();
        tfKerdes = new javax.swing.JTextField();
        lblKerdes = new javax.swing.JLabel();
        lblValasz = new javax.swing.JLabel();
        tfValasz = new javax.swing.JTextField();
        btnEllenoriz = new javax.swing.JButton();
        tfVisszajelzes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblKerdes.setText("Kérdés:");

        lblValasz.setText("Válasz:");

        btnEllenoriz.setText("Ellenőriz");

        javax.swing.GroupLayout pnlAblakLayout = new javax.swing.GroupLayout(pnlAblak);
        pnlAblak.setLayout(pnlAblakLayout);
        pnlAblakLayout.setHorizontalGroup(
            pnlAblakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAblakLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAblakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblValasz)
                    .addGroup(pnlAblakLayout.createSequentialGroup()
                        .addComponent(cbMuveletek, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKerdes)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAblakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfKerdes)
                    .addGroup(pnlAblakLayout.createSequentialGroup()
                        .addGroup(pnlAblakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfVisszajelzes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(tfValasz, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEllenoriz)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlAblakLayout.setVerticalGroup(
            pnlAblakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAblakLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAblakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMuveletek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfKerdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKerdes))
                .addGap(26, 26, 26)
                .addGroup(pnlAblakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValasz)
                    .addComponent(tfValasz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEllenoriz))
                .addGap(64, 64, 64)
                .addComponent(tfVisszajelzes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAblak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAblak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ablak().setVisible(true);
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEllenoriz;
    private javax.swing.JComboBox<String> cbMuveletek;
    private javax.swing.JLabel lblKerdes;
    private javax.swing.JLabel lblValasz;
    private javax.swing.JPanel pnlAblak;
    private javax.swing.JTextField tfKerdes;
    private javax.swing.JTextField tfValasz;
    private javax.swing.JTextField tfVisszajelzes;
    // End of variables declaration//GEN-END:variables
}
